# Generated by Django 2.1rc1 on 2019-01-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owl',
        ),
    ]
