# Generated by Django 2.1rc1 on 2019-01-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0003_auto_20190103_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='concepts',
            field=models.FileField(default='settings.MEDIA_ROOT/los/los.txt', upload_to=''),
        ),
    ]
